name: Build

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: bowl-builder/package-lock.json
      - name: Install dependencies
        run: npm ci
        working-directory: bowl-builder
      - name: Build
        run: npm run build
        working-directory: bowl-builder
